# Generated by Django 3.2.12 on 2022-04-28 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tabela'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Tipo de Pagamento')),
            ],
            options={
                'verbose_name_plural': 'Forma de Pagamentos',
            },
        ),
        migrations.AlterField(
            model_name='tabela',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='Rotativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(verbose_name='Entrada')),
                ('data_saida', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Total')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.formapagamento', verbose_name='Tipo de Pagamento')),
                ('id_Veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veículo')),
                ('id_tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tabela', verbose_name='Tarifa')),
            ],
            options={
                'verbose_name_plural': 'Rotativos',
            },
        ),
        migrations.CreateModel(
            name='Mensalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formapagamento', verbose_name='Tipo de Pagamento')),
                ('id_Tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tabela', verbose_name='Tarifa')),
                ('id_Veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name_plural': 'Mensalistas',
            },
        ),
    ]
