# Generated by Django 3.2.12 on 2022-05-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220427_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='hora_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hora Adicional'),
        ),
    ]
