# Generated by Django 3.2.12 on 2022-05-12 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tabela_hora_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='moto',
            field=models.BooleanField(default='False', verbose_name='Moto'),
        ),
        migrations.AlterField(
            model_name='rotativo',
            name='id_Veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veículo'),
        ),
    ]
